import type {
  ChecklistItem,
  CommsFlag,
  CommsMessage,
  CommsPhase,
  SwapRow,
} from "./masterclass-review-comms-types";

/**
 * Source: vp-webinars/reports/2026-10-01-webinar-registration-comms-map.md
 * (Full copy + "Live verification 2026-10-01"), the Oct 6 decision register and
 * the Oct 13 full-cutover check (vp-webinars/event-log/2026-10-13.md, 2026-10-07).
 * Where the live section corrects timing or copy, the live version is used.
 * Placeholders: {first}, {webinar date}, {zoom link}, {registration email},
 * {link: where it goes}, {Q&A date}.
 */

const text = (...lines: string[]): string => lines.join("\n");

const ANTHONY_TEXT = "Anthony (text line ending 9273)";
const ANTHONY_EMAIL = "Anthony Kolodziej";

const UTM_ISSUE =
  "its short link still carries an old room's utm_content (sept15_end_cta or sept01), so replay and booking traffic is credited to the wrong event";
const UTM_FIX =
  "point the Bitly link at the site replay page (vendingpreneurs.com/masterclass-replay-dna or -adnb) with this week's utm_content (oct06_end_cta until the Oct 13 room, then oct13_end_cta)";
const EXPIRY_ISSUE =
  "the message says the replay comes down Sunday at 9 PM CT while the site and GHL countdown said 11 PM";
const EXPIRY_FIX =
  "use 9 PM everywhere: the site is now set to 9 PM, and GHL's countdown (owner Ivan) must also say 9 PM";

const UTM_FLAG: CommsFlag = {
  issue:
    "The short link in this message still carries an old room's utm_content, so replay and booking traffic is credited to the wrong event.",
  fix: "Point the Bitly link at the site replay page with this week's utm_content (oct06_end_cta until the Oct 13 room, then oct13_end_cta).",
  owner: "Ivan",
  due: "Wed Oct 7",
};

const CST_FLAG: CommsFlag = {
  issue:
    "Earlier rooms printed the webinar time as 7:30 PM CST although the room is CDT.",
  fix: "The live custom value now reads CDT; confirm the sent email shows CDT and never CST.",
  owner: "Ivan",
  due: "Wed Oct 7",
};

export const COMMS_MESSAGES: readonly CommsMessage[] = [
  // ---------------------------------------------------------------- register
  {
    id: "S1",
    phase: "register",
    when: "6 seconds after signing up",
    channel: "sms",
    from: ANTHONY_TEXT,
    body: text(
      "Hi {first}, it's Anthony! Your seat is confirmed for {webinar date}. Stoked to have you learn more about starting a vending route!",
      "Reply STOP to unsubscribe",
      "- VendingPreneurs",
    ),
    verbatim: true,
  },
  {
    id: "E1",
    phase: "register",
    when: "about 7 seconds after signing up",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "👍 You're in!",
    body: text(
      "Vending Starts Here...",
      "",
      "Hey {first},",
      "",
      "You're in.",
      "",
      "Thanks for registering for the masterclass on {webinar date}.",
      "",
      "I have one favor to ask... Could you hit reply and tell me what made you sign up for my class. I read every response. It helps me shape the live Q&A around the questions, concerns, and goals that people actually have.",
      "",
      "Between now and then, I'll send you a few short emails and texts to help you get the most out of this, so please make sure you whitelist this address, anthony@webinar.vendingpreneurs.co.",
      "",
      "You also should have received an email from Zoom with your individual link to get you into the class. Let me know if you didn't.",
      "",
      "During the training we'll cover things like:",
      "* The mistake that causes most new operators to waste months.",
      "* How I evaluate whether a location is worth pursuing before spending money on equipment.",
      "* What the first 90 days actually look like.",
      "* Whether building a vending business actually makes sense for your goals, schedule, and lifestyle.",
      "",
      "My goal isn't to convince you vending is for everyone.",
      "It's to give you enough information to decide whether it's right for you.",
      "",
      "See you on {webinar date},",
      "Anthony",
      "",
      "P.S. Do yourself a favor and block off the time on your calendar now. It's a lot easier to keep a promise you make to yourself today than one you make five minutes before we go live.",
      "Click here to add to your calendar {link: add-to-calendar (AddEvent)}",
    ),
    verbatim: true,
    links: ["Add-to-calendar link (AddEvent)"],
  },
  {
    id: "Z1",
    phase: "register",
    when: "about 8 seconds after signing up",
    channel: "zoom",
    from: "Zoom",
    subject: "Zoom registration confirmation",
    body: "Zoom's own confirmation email with the person's personal join link (also written back to their contact record). Zoom's template; not captured.",
    verbatim: false,
  },
  {
    id: "S2",
    phase: "register",
    when: "2 minutes after signing up",
    channel: "sms",
    from: ANTHONY_TEXT,
    body: text(
      "Can you do me a favor? Check your spam and promotions folder for an email from anthony@webinar.vendingpreneurs.co and whitelist it.",
      "",
      "Once you find it, reply YES so I know it made it through.",
      "",
      "Reply STOP to unsubscribe",
    ),
    verbatim: true,
  },
  {
    id: "E2",
    phase: "register",
    when: "12 minutes after signing up (stopped firing on Sept 30; must stay off)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "No hard feelings",
    body: text(
      "{first},",
      "You passed on $47 OFFER, and that's completely fine. Neither one is right for everyone, and I'd rather you pass than buy something that doesn't actually fit where you're at.",
      "That doesn't mean the door's closed. If you're still figuring out whether building something of your own is the right move, here's where I'd point you instead:",
      "→ Watch real operator stories {link: operator stories} — what's actually working, every week, no pitch attached.",
      "→ Join The Entrepreneur Collective {link: community} — our free community for people who want more freedom, ownership, and options in their life.",
      "No pressure, no follow-up sales email tomorrow. Just a place to keep learning while you figure out your next step.",
      "Talk soon,",
      "Anthony",
    ),
    verbatim: true,
    links: ["Operator stories", "The Entrepreneur Collective (community)"],
    flag: {
      issue:
        "This Playbook-decline email went to nearly everyone 12 minutes after sign-up, saying they passed on a $47 offer when the Playbook is $67 and most had never seen it.",
      fix: "Keep it off: confirm in GHL that the step is removed or disabled, not just paused by a wait step.",
      owner: "Ivan",
      due: "Wed Oct 7",
    },
  },
  {
    id: "E3",
    phase: "register",
    when: "about 3 hours after signing up (older rooms: about 40 minutes)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "Before you spend an hour with me…",
    body: text(
      "I figured I should properly introduce myself.",
      "",
      "Hey {first},",
      "",
      "If we've never met before, you're probably wondering... Who is Anthony, and why should I trust him? Totally fair question, here's the TL;DR.",
      "",
      "In August 2023, I was head of business development at a real estate boutique firm. I was making well over six figures. Amazing wife, kiddos, house… On paper, life looked pretty good.",
      "",
      "But when my colleague got laid off, I knew I was next",
      "",
      "Instead of finding another W-2 job and hoping history wouldn't repeat itself, I decided to build something I actually owned. The criteria I was looking for: I wanted to own my own time, be able to involve my kids and wife, not get into a ton of debt to start, and actually own something I could grow.",
      "",
      "Today I operate 47 locations and 84 machines. Last month the business generated $116,352.88.* If you're curious, here's a conversation Mike Hoffmann and I had where I share more of that journey and how it all came together {link: Mike and Anthony conversation video}.",
      "",
      "Let me be clear something up for you, I didn't do this alone.",
      "",
      "What accelerated everything was having a proven blueprint and a community of operators who had already solved the problems I was about to face. I didn't have to guess which locations worked, how to close them, or what mistakes to avoid. I just followed the system and kept taking the next step.",
      "",
      "That's exactly what I'm going to walk you through on {webinar date}.",
      "",
      "I'll show you the framework I used to build my route, the mistakes I'd avoid if I were starting over today, and what the first 90 days actually looked like.",
      "",
      "Maybe people look at your life and think you've already made it. You have a good career. Your business is doing well. You're raising a family. Maybe you've even retired. But if there's still a part of you that wants to build something you own, I think you'll get a lot out of this training.",
      "",
      "I'll see you live on {webinar date}.",
      "",
      "Anthony Kolodziej / Vendingpreneurs",
      "",
      "PS: Hit reply and let me know what your criteria is. As mentioned above, owning my time was a big one for me.",
      "PSS: Click here to add your calendar {link: add-to-calendar (AddEvent)}... there's a way better chance you're actually going to show up.",
    ),
    verbatim: true,
    links: [
      "Mike and Anthony conversation video",
      "Add-to-calendar link (AddEvent)",
    ],
    flag: CST_FLAG,
  },

  // ------------------------------------------------------------------ before
  {
    id: "E4",
    phase: "before",
    when: "about 5 days before (Thursday about 11 AM CT)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "Hmm, sound familiar?",
    body: text(
      "Hey {first},",
      "",
      'A huge misconception I hear about vending is that there\'s a certain "type" of person who succeeds.',
      "Spoiler alert, there isn't.",
      "",
      "Matt managed a software sales team. AI was changing his industry, and he wanted to build something tangible that he actually controlled.",
      "Shannon had a successful W-2 career. She wasn't looking to quit overnight. She just wanted to build another stream of income that fit around her life.",
      "Mallorie is a physician assistant. She and her husband wanted something they could build together and eventually involve their kids in.",
      "Lane worked 12-hour shifts as a geologist, rotating days and nights with a three-hour daily commute. He wanted more control over his time with his family.",
      "",
      "They all had different backgrounds and reasons why they wanted to build something they owned.",
      "But the main thing they had in common… They stopped waiting until they had everything figured out.",
      "",
      "On {webinar date}, I'm going to walk you through the same business they chose, why it made sense for their situations, and what getting started actually looked like.",
      "",
      "My guess is you'll probably see a little of yourself in one of their stories.",
      "",
      "I'll see you there,",
      "Anthony Kolodziej",
      "",
      "P.S. Hit reply and let me know what background you're coming from and why building something on the side resonates with you.",
    ),
    verbatim: true,
    flag: CST_FLAG,
  },
  {
    id: "E5",
    phase: "before",
    when: "about 4 days before (103 hours)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "Sorry, I have homework for you.",
    body: text(
      "{first},",
      "",
      "Don't hate me, but I'm gonna give you some homework.",
      "",
      "This isn't just a fluff assignment. Honestly, it completely changed the way I look at potential vending locations.",
      "",
      "Drive by any location you have in mind and count the cars in the parking lot. That's it. If you have your kids with you, make it a game.",
      "",
      "This is called the parking lot test. It's free, it doesn't take too long, and it's the first filter I teach every new operator before they spend a single dollar.",
      "",
      "Can you hit reply back to this email and let me know when you finished it?",
      "",
      'parking lot test. 20 cars pass. 20-50 cars moderate. 50 cars high potential. [image: "50 or more - high potential | 20 to 50 - moderate potential | Under 20 - pass"]',
      "",
      "On {webinar date}, I'll show you exactly how this business works. You'll leave understanding how to find locations, what machine to place where, the honest margins and the grit it takes to do this.",
      "",
      "This isn't based around hypotheticals. These are real experiences and lessons I've learned, and anyone who is thinking about starting a vending route needs to know them.",
      "",
      "Anthony Kolodziej / Vendingpreneurs",
      "",
      "P.S. And for anyone who shows up live, I'm giving away 3 bonuses to help you start your route.",
      "P.S.S. Have you saved the date on your calendar yet, if not click here {link: add-to-calendar (AddEvent)}.",
    ),
    verbatim: true,
    links: ["Add-to-calendar link (AddEvent)"],
    flag: CST_FLAG,
  },
  {
    id: "E27",
    phase: "before",
    when: "about 3.4 days before (Saturday about 10 AM CDT)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "Quick reminder of what's inside {webinar date}",
    body: text(
      "Same class, same content. Available right now if you're ready.",
      "",
      "{first}, Here's a reminder of what we're covering on {webinar date}: the mistake that costs new operators months, how I judge a location before I ever buy equipment, and whether this actually fits your schedule and goals. I'm not trying to convince you vending's for everyone. I just want to give you enough to decide for yourself.",
      "Here's the thing. Some of you already have enough. You've been following along, you know what you're looking for, and the live class isn't going to tell you anything you haven't already figured out for yourself. If that's you, you don't have to wait for {webinar date}. Enroll in Mike Hoffmann Playbook here {link: Playbook page}. It's the same program, same price, open right now. You'll still get the invite to the live class and the Q&A either way. No reason to sit on it for a few more days if you're already there.",
      "Anthony",
    ),
    verbatim: true,
    links: ["Playbook page (GHL)"],
    flag: {
      issue:
        "The Playbook link still goes to the GoHighLevel /playbook page, so these clicks skip the site page the board measures.",
      fix: "Change the link in this email to vendingpreneurs.com/playbook (keep the utm parameters). Link only; the workflow stays as is.",
      owner: "Ivan",
      due: "Thu Oct 8",
    },
  },
  {
    id: "S3",
    phase: "before",
    when: "about 2.75 days before (66 hours)",
    channel: "sms",
    from: ANTHONY_TEXT,
    body: text(
      "Don't hate me, but checking in on your homework assignment. 😁 How'd the parking lot test go? If you don't know what I'm talking about check your email.",
      "And if you didn't do it, no worries. I'll fill you in at the class.",
    ),
    verbatim: true,
  },
  {
    id: "E6",
    phase: "before",
    when: "about 2 days before (Sunday about 7:30 PM CDT, 48.5 hours)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "If you couldn't work for two weeks",
    body: text(
      "{first},",
      "",
      "If all your PTO and sick time ran out and you couldn't work for two weeks, would your income take a dip?",
      'The majority of people I know would say, "unfortunately, yes…"',
      "",
      "I mean, you're probably doing good. Comfortable job. Decent income. Bills getting paid. Maybe even a little money going into savings each month.",
      "And there's absolutely nothing wrong with that. Honestly, that's where you want to be sitting.",
      "",
      "But at the end of the day, whether it's an employer, your biggest client, a busy season, or an algorithm, someone else still has a say in what you make and where you make it.",
      "",
      "That's why building something in addition to what you already have going on is the biggest flex you can do in 2026. Preferably something that can generate income whether you're working that day or not.",
      "",
      "That's what we're going to talk about on {webinar date}. Not because vending is some magic solution. But it's a real business that fits the criteria most of us are looking for.",
      "",
      "During the masterclass, I'll show you:",
      "* How I evaluate locations before spending a dollar on equipment.",
      "* The two plays we've used to land locations.",
      "* What the first 30–90 days realistically look like.",
      "* And how to decide whether this business actually fits your life and goals.",
      "",
      "Loop your spouse or business partner (whoever you share financial decisions with) in now. Bring them to the class. If for some reason they aren't able to be next to you, you're welcome to hit reply and send me their name and email, and I'll invite them to the class myself.",
      "",
      "I'll see you on {webinar date}.",
      "Anthony Kolodziej",
      "",
      "P.S. You don't have to decide whether vending is right for you before the webinar. You just have to decide whether it's worth spending one hour finding out.",
    ),
    verbatim: true,
  },
  {
    id: "S4",
    phase: "before",
    when: "24 hours before",
    channel: "sms",
    from: ANTHONY_TEXT,
    body: text(
      "Hey, the masterclass is tomorrow at 7:30 PM Central Time.",
      "Remember the video you saw after registering for the class. I want to show you that again {link: confirmation page (GHL)}",
      "Once you finish it, let me know what that would do for you!",
      "Reply STOP to unsubscribe",
    ),
    verbatim: true,
    links: ["Confirmation page (GHL)"],
    flag: {
      issue:
        "The link still goes to the GoHighLevel confirmation page, not the site page people saw after signing up on the site.",
      fix: "Change the link in this text to vendingpreneurs.com/masterclass-confirmed. Link only; the workflow stays as is.",
      owner: "Ivan",
      due: "Thu Oct 8",
    },
  },
  {
    id: "E7",
    phase: "before",
    when: "24 hours before (sent with the day-before text, includes the Zoom link)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "The hardest part isn't building",
    body: text(
      "Most ppl don't get that far",
      "",
      "{first},",
      "",
      "If you're just dipping your toes in the world of entrepreneurship, this might come as a surprise for you. And if you're already in that world, skip to the next part.",
      "",
      "Most people think building a business is the hardest part. The truth is, most people never get that far. They get stuck trying to decide what to build.",
      "",
      "If you're anything like I was, you're probably looking at real estate, buying a small business, e-comm, investing in a franchise, dropshipping… Maybe a dozen other ideas too.",
      "",
      "You compare one opportunity against another, hoping the next podcast, YouTube video, or article will finally give you enough confidence to pull the trigger. Only to find yourself three hours later researching all over again.",
      "",
      "I'm gonna tell you a secret, though. There are only businesses that fit your goals, your schedule, and the life you're trying to build.",
      "",
      'At some point, you need to stop asking, "What\'s the perfect business?" And started asking, "Can this help me build the life I actually want?"',
      "",
      "Tomorrow, my goal isn't to convince you that vending is the perfect business. My goal is to help you decide whether it's the right business for you.",
      "",
      "I'll see you tomorrow.",
      "",
      "Anthony Kolodziej",
      "",
      "P.S. Hit reply and let me know what your #1 take away you're hoping to get from the class.",
    ),
    verbatim: true,
  },
  {
    id: "V1",
    phase: "before",
    when: "24 hours before (set up; not seen firing)",
    channel: "voice",
    from: ANTHONY_EMAIL,
    body: 'Ringless voicemail drop (workflow "Anthony Voice Day Before"). Audio not captured.',
    verbatim: false,
    flag: {
      issue:
        "The day-before voicemail workflow is published but no voicemail was recorded at 24 hours before on any of the 495 Sept 29 contacts.",
      fix: "Confirm in GHL whether this voicemail is meant to send, and fix or retire the workflow.",
      owner: "Ivan",
      due: "Wed Oct 7",
    },
  },

  // ------------------------------------------------------------------- dayof
  {
    id: "S5",
    phase: "dayof",
    when: "3 hours before (4:30 PM CT)",
    channel: "sms",
    from: ANTHONY_TEXT,
    body: text(
      "We're on at {webinar date}. Message me back on a scale of 1 - 10 how excited you are.",
      "I'll go first.. 10.",
      "Reply STOP to unsubscribe",
      "- VendingPreneurs",
    ),
    verbatim: true,
  },
  {
    id: "S6",
    phase: "dayof",
    when: "2 hours before",
    channel: "sms",
    from: ANTHONY_TEXT,
    body: text(
      "Hey {first}, we're live in about 2 hours.",
      "",
      "If you can, grab your spouse, business partner, or anyone you're thinking about building this with.",
      "",
      "See you in there: {zoom link}",
      "",
      "Try to join from a laptop or desktop so you can see everything clearly.",
    ),
    verbatim: true,
    links: ["Personal Zoom link"],
  },
  {
    id: "E9",
    phase: "dayof",
    when: "2 hours before",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "We start in 2 hours",
    body: text(
      "{first},",
      "We're live in about 2 hours.",
      "If you can, join from a laptop or desktop so you can see everything clearly. I'll be sharing my screen throughout the training.",
      "We'll start right on time, and I'll stick around afterward for live Q&A.",
      "Here's your link to join: {zoom link}",
      "Looking forward to seeing you there.",
      "Anthony",
      "P.S. I'll also be giving away the three resources I mentioned during registration to everyone who joins live.",
    ),
    verbatim: true,
    links: ["Personal Zoom link"],
  },
  {
    id: "E10",
    phase: "dayof",
    when: "30 minutes before (measured about 26 minutes)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "We start in 30 minutes",
    body: text(
      "{first},",
      "We're live in 30 minutes.",
      "If you can, join from a laptop or desktop so you can see everything clearly.",
      "We'll start right on time at {webinar date}.",
      "Join here: {zoom link}",
      "See you soon,",
      "Anthony",
    ),
    verbatim: true,
    links: ["Personal Zoom link"],
  },
  {
    id: "S7",
    phase: "dayof",
    when: "15 minutes before",
    channel: "sms",
    from: ANTHONY_TEXT,
    body: text(
      "We start in 15 minutes, {first}.",
      "",
      "I'll also be giving away the 3 free bonuses I mentioned to everyone who joins live.",
      "",
      "Here's your link: {zoom link}",
      "",
      "If you can, join from a laptop or desktop since I'll be sharing my screen throughout the class.",
    ),
    verbatim: true,
    links: ["Personal Zoom link"],
    flag: {
      issue:
        "It promises 3 free live bonuses, but nobody has named the third one and the booked-call email lists only two.",
      fix: "Anthony names the third bonus and says whether the fast-action discount exists; then match this text, the confirmation page and the booked email.",
      owner: "Anthony",
      due: "Wed Oct 7",
    },
  },
  {
    id: "E11",
    phase: "dayof",
    when: "at the 7:30 PM start",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "We're live",
    body: text(
      "{first},",
      "We're live.",
      "If you're free, come join us. You're right on time.",
      "Join here: {zoom link}",
      "See you in there,",
      "Anthony",
    ),
    verbatim: true,
    links: ["Personal Zoom link"],
  },
  {
    id: "S8",
    phase: "dayof",
    when: "at the 7:30 PM start",
    channel: "sms",
    from: ANTHONY_TEXT,
    body: text(
      "{first}, we're live! Here's your direct join link: {zoom link}",
      "",
      "You're right on time. See you in the room!",
    ),
    verbatim: true,
    links: ["Personal Zoom link"],
  },
  {
    id: "E12",
    phase: "dayof",
    when: "about 15 minutes after the start",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "Still time to join",
    body: text(
      "{first},",
      "We started about 15 minutes ago, and it's not too late to jump in.",
      "You're still early enough to catch the majority of the training, and I'll be answering questions live afterward.",
      "If you can, join from a laptop or desktop so you can follow along as I share my screen.",
      "Click here to join: {zoom link}",
      "See you in there,",
      "Anthony",
    ),
    verbatim: true,
    links: ["Personal Zoom link"],
  },
  {
    id: "S9",
    phase: "dayof",
    when: "about 20 minutes after the start (set for 15)",
    channel: "sms",
    from: ANTHONY_TEXT,
    body: text(
      "We started Vending Masterclass about 15 minutes ago, and it's not too late to jump in.",
      "{zoom link}",
    ),
    verbatim: true,
    links: ["Personal Zoom link"],
  },
  {
    id: "S10",
    phase: "dayof",
    when: "about 26 minutes after the start (set for 30)",
    channel: "sms",
    from: ANTHONY_TEXT,
    body: text(
      "We are 30 mins in, and it's not too late to jump in.",
      "{zoom link}",
    ),
    verbatim: true,
    links: ["Personal Zoom link"],
  },

  // ---------------------------------------------------------------- attended
  {
    id: "E13",
    phase: "attended",
    when: "12 hours after the start (7:30 AM the next morning)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "you were there",
    body: text(
      "Now what?",
      "",
      "Hey {first}, Thanks for showing up. I loved the energy in the room. Here's the 🎥 replay {link: replay page} You've probably been turning over what we covered. That's normal. I did the same thing deciding if vending was right for me. I didn't need another podcast, or another idea to compare it. I needed to answer one question: is this the right business for the life I want to build? If you're wrestling with that same question, the next step is a quick call with our team. They'll answer your questions and help you figure out if vending makes sense for you. If it doesn't, they'll tell you that too. Find a time here: {link: book a call (adnb-booking-calendar)} If you still want a few things cleared up, I am doing a cameras-on Q&A. We can chat and work through what's coming up for you when it comes to starting your business. Here's the link {link: Q&A Zoom registration} Reply back and let me know if I'll see you there. Talk soon, Anthony Kolodziej",
    ),
    verbatim: true,
    links: [
      "Replay page (GHL)",
      "Book a call (adnb-booking-calendar short link)",
      "Q&A Zoom registration",
    ],
    flag: {
      issue:
        "The booking short link carries an old room's utm_content and its page anchor is cut off by one character, so it may not scroll to the booking section.",
      fix: "Point the Bitly link at vendingpreneurs.com/masterclass-replay-adnb with oct06_end_cta; the site page needs no anchor.",
      owner: "Ivan",
      due: "Wed Oct 7",
    },
  },
  {
    id: "V2",
    phase: "attended",
    when: "18 hours after the start (about 1:30 PM the next day), just before the text",
    channel: "voice",
    from: ANTHONY_EMAIL,
    body: "Ringless voicemail drop for people who attended but did not book. Audio not captured.",
    verbatim: false,
  },
  {
    id: "S11",
    phase: "attended",
    when: "18 hours after the start (about 1:30 PM the next day)",
    channel: "sms",
    from: ANTHONY_TEXT,
    body: text(
      "Hey! I just left you a voicemail. Thanks for joining the class.",
      "Honestly, we covered a lot and I totally get if you have some questions about vending, the community, or even whether this makes sense for you.",
      "So I'm putting together a small, cameras on, Q&A for anyone who wants to come back, ask me whatever's on their mind, and get some straight answers.",
      "The Q&A is on {Q&A date}",
      "Here's the link: {link: Q&A Zoom registration}",
      "Reply STOP to unsubscribe",
      "- VendingPreneurs",
    ),
    verbatim: true,
    links: ["Q&A Zoom registration"],
  },
  {
    id: "S12",
    phase: "attended",
    when: "34 hours after the start (Thursday about 5:30 AM)",
    channel: "sms",
    from: ANTHONY_TEXT,
    body: text(
      "{first}, the 90-Day Blueprint and Route Builder were delivered to your inbox yesterday. Did you get them?",
      "I also sent you the replay, so check your inbox. We still have some spots available this week for the free market fit calls: {link: book a call (adnb-sms)}",
      "Reply STOP to unsubscribe",
    ),
    verbatim: true,
    links: ["Book a call (adnb-sms short link)"],
    flag: {
      issue:
        "It says the 90-Day Blueprint and Route Builder were delivered yesterday, but none of the attended emails contain them (only the booked email does), it goes out at 5:30 AM, and its short link has a stale utm_content.",
      fix: 'Attach both to the "you were there" email or drop the claim, move the send to a daytime slot, and point the Bitly link at the site replay page with oct06_end_cta.',
      owner: "Ivan",
      due: "Wed Oct 7",
    },
  },
  {
    id: "E14",
    phase: "attended",
    when: "36 hours after the start (7:30 AM two days after)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "What's your plan?",
    body: text(
      "Hey,",
      "I've been thinking about everyone who joined the webinar.",
      "Some people will decide vending isn't for them. Some will decide it is.",
      "Both are good outcomes.",
      "The only outcome I don't want for you is spending the next few months wondering if you should've done something.",
      "When I first found vending, I kept telling myself that another week of research would give me more clarity. It didn't.",
      "What finally moved me forward was talking through my situation with someone who'd already been there.",
      "If you're still figuring out whether vending is the right fit for you, my team is happy to have that conversation.",
      "Start the conversation: {link: book a call (adnb-booking-calendar)}",
      "Talk soon,",
      "Anthony",
      "P.S. The replay is still available until Sunday at 9 PM CT if you'd like to revisit anything before it's taken down.",
    ),
    verbatim: true,
    links: ["Book a call (adnb-booking-calendar short link)"],
    flag: {
      issue: EXPIRY_ISSUE + ", and " + UTM_ISSUE + ".",
      fix: "Keep 9 PM: " + EXPIRY_FIX + "; and " + UTM_FIX + ".",
      owner: "Ivan",
      due: "Wed Oct 7",
    },
  },
  {
    id: "E15",
    phase: "attended",
    when: "2 days after the start (measured on a noon room)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "Youtube can't do this",
    body: text(
      "HEY {first},",
      "One thing I didn't fully appreciate when I first got into vending was the difference between information and implementation.",
      "I could watch YouTube videos all day.",
      "I could listen to podcasts.",
      "I could read forum posts.",
      "But none of them could tell me what my next step should be.",
      "That's what made the biggest difference for me.",
      "Not more information. Having people who'd already built the business help me avoid the mistakes they had already made.",
      "If you're still deciding whether Vendingpreneurs is the right fit, the best next step is to talk it through with our team.",
      "You can also revisit the replay from the same page if you'd like to go back through the training: {link: replay page (adnb-replay)}",
      "Talk soon,",
      "Anthony",
      "P.S. If you decided to start tomorrow, what's the first thing you'd want help with?",
    ),
    verbatim: true,
    links: ["Replay page (adnb-replay short link)"],
    flag: UTM_FLAG,
  },
  {
    id: "E16",
    phase: "attended",
    when: "3 days after the start (measured on a noon room)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "One thing I've noticed about our community",
    body: text(
      "Hey {first},",
      "Ya know something I've noticed about our community members?",
      "They all come from different backgrounds.",
      "But they have one thing in common.",
      "They didn't want to figure everything out by themselves.",
      "That's why we built Vendingpreneurs the way we did.",
      "Because sometimes you just need someone who's a few steps ahead to help you avoid the mistakes they already made.",
      "If you're wondering what that could look like for your situation, we'd be happy to talk it through with you.",
      "{link: book a call (adnb-booking-calendar)}",
      "Talk soon,",
      "Anthony",
      "P.S. If you could get help with one part of building a vending business, what would it be? Finding locations? Choosing machines? Something else?",
    ),
    verbatim: true,
    links: ["Book a call (adnb-booking-calendar short link)"],
    flag: UTM_FLAG,
  },
  {
    id: "E17",
    phase: "attended",
    when: "4 days after the start (measured on a noon room)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "One last thought",
    body: text(
      "Hey {first},",
      "This will be my last email about the class.",
      "If there's one thing I hope you took away, it's that building another income stream isn't about finding the perfect business.",
      "It's about finding the right vehicle for the life you want to build.",
      "Maybe that's vending.",
      "Maybe it isn't.",
      'Either way, I hope you make a decision you feel good about instead of staying stuck wondering "what if?"',
      "If you'd like to talk through your situation, my team is here to help.",
      "{link: book a call (adnb-booking-calendar)}",
      "Thanks again for spending time with me.",
      "Anthony",
      "P.S. Whether you decide to move forward or not, I'd love to know: what was the biggest takeaway from the class? Just hit reply and let me know.",
    ),
    verbatim: true,
    links: ["Book a call (adnb-booking-calendar short link)"],
    flag: UTM_FLAG,
  },
  {
    id: "S13",
    phase: "attended",
    when: "5 days after the start (Sunday; measured on a noon room)",
    channel: "sms",
    from: ANTHONY_TEXT,
    body: text(
      "{first}, last reminder, the replay comes down tonight at 9pm CT.",
      "You don't have to decide today that vending is right for you. But if you're still thinking about it, I think it's worth finding out.",
      "Watch the replay in your inbox or book a free call with my team here: {link: book a call (adnb-sms)}",
      "-Anthony",
    ),
    verbatim: true,
    links: ["Book a call (adnb-sms short link)"],
    flag: {
      issue: EXPIRY_ISSUE + ", and " + UTM_ISSUE + ".",
      fix: "Keep 9 PM: " + EXPIRY_FIX + "; and " + UTM_FIX + ".",
      owner: "Ivan",
      due: "Wed Oct 7",
    },
  },
  {
    id: "S14",
    phase: "attended",
    when: "6 days after the start (measured on a noon room)",
    channel: "sms",
    from: ANTHONY_TEXT,
    body: text(
      "Let me ask you this... if you decided not to book after coming to the class last week, what held you back?",
      "a. the investment",
      "b. the time commitment",
      "c. unsure if it will work for me",
      "-Anthony",
    ),
    verbatim: true,
  },

  // ------------------------------------------------------------------ missed
  {
    id: "E18",
    phase: "missed",
    when: "12 hours after the start (7:30 AM the next morning)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "bummed we missed you",
    body: text(
      "Hey {first},",
      "I noticed you weren't able to make the masterclass yesterday.",
      "No worries. Life happens.",
      "I'm keeping the replay available through Sunday at 9:00 PM CT, and I wanted to make sure you had a chance to watch it if you're still interested.",
      "One thing I tried to do in this training was cut through a lot of the noise that's out there.",
      "If you've been wondering whether vending is actually worth pursuing, my goal wasn't to convince you. It was to help you decide whether it's the right fit for you.",
      "You can watch the replay here: {link: replay page (dna-replay)}",
      "Talk soon,",
      "Anthony Kolodziej",
      "P.S. What about vending interests you the most?",
    ),
    verbatim: true,
    links: ["Replay page (dna-replay short link)"],
    flag: {
      issue: EXPIRY_ISSUE + ", and " + UTM_ISSUE + ".",
      fix: "Keep 9 PM: " + EXPIRY_FIX + "; and " + UTM_FIX + ".",
      owner: "Ivan",
      due: "Wed Oct 7",
    },
  },
  {
    id: "S15",
    phase: "missed",
    when: "18 hours after the start (about 1:30 PM the next day)",
    channel: "sms",
    from: ANTHONY_TEXT,
    body: text(
      "Hey {first}, I saved the replay from the class earlier in case you still wanted to check it out:",
      "{link: replay page (dna-sms-replay)}",
      "I'll keep it up through Sunday at 9pm CT.",
      "-Anthony",
    ),
    verbatim: true,
    links: ["Replay page (dna-sms-replay short link)"],
    flag: {
      issue: EXPIRY_ISSUE + ", and " + UTM_ISSUE + ".",
      fix: "Keep 9 PM: " + EXPIRY_FIX + "; and " + UTM_FIX + ".",
      owner: "Ivan",
      due: "Wed Oct 7",
    },
  },
  {
    id: "E28",
    phase: "missed",
    when: "24 hours after the start (7:30 PM the next day)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "I thought I needed more time",
    body: text(
      "More time never showed up with the answer.",
      "",
      "Hey {first}, For a long time, I thought another week of research and mulling it over would give me more clarity. Then another week turned into another month. Nothing changed. Looking back, I wasn't missing information. I was trying to eliminate every bit of uncertainty before making a decision. But you know what? You're probably never going to feel 100% certain. At some point, you have to decide whether you know enough to take the next step. For me, that meant getting out of research mode and actually exploring what vending could look like. If you haven't had a chance to watch it yet, here's the replay: {link: replay page (dna-replay)} I'll keep it available until Sunday at 9:00 PM CT. Anthony",
    ),
    verbatim: true,
    links: ["Replay page (dna-replay short link)"],
    flag: {
      issue: EXPIRY_ISSUE + ", and " + UTM_ISSUE + ".",
      fix: "Keep 9 PM: " + EXPIRY_FIX + "; and " + UTM_FIX + ".",
      owner: "Ivan",
      due: "Wed Oct 7",
    },
  },
  {
    id: "E19",
    phase: "missed",
    when: "2 days after the start (measured on a noon room)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "I almost went all in on house flipping",
    body: text(
      "Hey {first},",
      "When I realized my financial future was tied to someone else's decisions, my first thought wasn't vending.",
      "It was real estate.",
      "Then I looked at laundromats. Car washes. Franchises. E-commerce.",
      "I wasn't looking for the perfect business. I was looking for one that fit my goals, my timeline, and the amount of capital I was comfortable investing.",
      "That's what kept bringing me back to vending.",
      "I explain why in the replay, because I think it's one of the most important decisions to make before investing in any business.",
      "Watch the replay {link: replay page (dna-replay)} 👈",
      "Talk soon,",
      "Anthony",
      "P.S. What matters most to you in a business right now? Time freedom? Cash flow? Something you can build with your family? Just hit reply. I'd love to know.",
    ),
    verbatim: true,
    links: ["Replay page (dna-replay short link)"],
    flag: {
      issue:
        'The Sept 29 room sent "I thought I needed more time" in this slot\'s place, so it is unclear whether this email still sends, and its short link has a stale utm_content.',
      fix: "Confirm the current missed-it email order in GHL, and point the Bitly link at the site replay page with oct06_end_cta.",
      owner: "Ivan",
      due: "Wed Oct 7",
    },
  },
  {
    id: "S16",
    phase: "missed",
    when: "2 days after the start (measured on a noon room)",
    channel: "sms",
    from: ANTHONY_TEXT,
    body: text(
      "{first}, you're probably not looking for vending.",
      "You're looking for options. Another source of income. Something you actually own.",
      "If that sounds like you, the replay is worth an hour before it comes down Sunday:",
      "{link: replay page (dna-sms-replay)}",
    ),
    verbatim: true,
    links: ["Replay page (dna-sms-replay short link)"],
    flag: UTM_FLAG,
  },
  {
    id: "E20",
    phase: "missed",
    when: "3 days after the start (measured on a noon room)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "They weren't looking for vending either.",
    body: text(
      "Hey {first},",
      "One of my favorite stories from our community is Graham and Katie's {link: Graham and Katie story}.",
      "Graham worked in medical device sales. Katie was raising their four kids at home.",
      "They weren't looking for vending.",
      "They were looking for a business they could build together. Something that fit their life, their goals, and the future they wanted for their family.",
      "That's what I've noticed about a lot of people in our community.",
      "Very few set out to own vending machines.",
      "They're looking for a way to build income they actually own.",
      "Vending just happens to be the path that made the most sense.",
      "I share more of Graham and Katie's story in the replay if you haven't had a chance to watch it yet.",
      "👀 Watch it here: {link: replay page (dna-replay)}",
      "Talk soon,",
      "Anthony",
      "P.S. If you could only have one, what's more important to you right now: more time or more income?",
    ),
    verbatim: true,
    links: ["Graham and Katie story", "Replay page (dna-replay short link)"],
    flag: UTM_FLAG,
  },
  {
    id: "S17",
    phase: "missed",
    when: "3 days after the start (measured on a noon room)",
    channel: "sms",
    from: ANTHONY_TEXT,
    body: text(
      "{first}, still comparing different ways to build another income stream?",
      "Give the replay a watch. If vending feels like something you want to explore, scroll down and book a free call with my team:",
      "{link: replay page (dna-sms-replay)}",
    ),
    verbatim: true,
    links: ["Replay page (dna-sms-replay short link)"],
    flag: UTM_FLAG,
  },
  {
    id: "E21",
    phase: "missed",
    when: "4 days after the start (Saturday; measured on a noon room)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "Before I take the replay down",
    body: text(
      "Hey {first},",
      "Tonight at 9:00 PM CT, I'll be taking the replay down.",
      "If you've been meaning to watch it, I'd set aside an hour before then.",
      "Inside, I walk through why I chose vending, how I built my route, and the framework I still use today.",
      "Here's the replay: {link: replay page (dna-replay)}",
      "If, after watching, you decide vending isn't the right fit for you, that's okay.",
      "My goal has never been to convince you.",
      "It's to help you decide.",
      "Thanks again for signing up.",
      "Talk soon,",
      "Anthony",
      "P.S. If now isn't the right time, I'd still love to stay in touch. We share new videos, real operator stories, and behind-the-scenes content every week.",
      "▶️ Subscribe on YouTube {link: YouTube channel (@Vendingpreneurs)}",
    ),
    verbatim: true,
    links: [
      "Replay page (dna-replay short link)",
      "YouTube channel (@Vendingpreneurs)",
    ],
    flag: {
      issue:
        'It says "Tonight" but goes out on Saturday, when the replay does not come down until Sunday; the 9 PM time also differed from the site\'s 11 PM, and its short link has a stale utm_content.',
      fix:
        'Say "Tomorrow" (or send it Sunday); keep 9 PM: ' +
        EXPIRY_FIX +
        "; and " +
        UTM_FIX +
        ".",
      owner: "Ivan",
      due: "Wed Oct 7",
    },
  },
  {
    id: "S18",
    phase: "missed",
    when: "4 days after the start (Saturday; measured on a noon room)",
    channel: "sms",
    from: ANTHONY_TEXT,
    body: text(
      "{first}, this isn't really about owning vending machines. It's about what another stream of income could do for you and your family.",
      "The replay comes down tomorrow. Give it a watch, and if vending feels worth exploring, scroll down and book a free call with my team:",
      "{link: replay page (dna-sms-replay)}",
      "-Anthony",
    ),
    verbatim: true,
    links: ["Replay page (dna-sms-replay short link)"],
    flag: UTM_FLAG,
  },
  {
    id: "S19",
    phase: "missed",
    when: "5 days after the start (Sunday; measured on a noon room)",
    channel: "sms",
    from: ANTHONY_TEXT,
    body: text(
      "{first}, if now isn't the right time, that's completely okay. But I'm curious—what's making now not the right time for you?",
      "Just hit reply and let me know.",
      "And if you want to keep learning, here are two places I'd start:",
      "YouTube: {link: YouTube channel (@Vendingpreneurs)}",
      "Free community: {link: Skool community (passiveincome)}",
      "-Anthony",
    ),
    verbatim: true,
    links: [
      "YouTube channel (@Vendingpreneurs)",
      "Skool community (passiveincome)",
    ],
  },

  // ------------------------------------------------------------------ booked
  {
    id: "E22",
    phase: "booked",
    when: "right after booking a call (about 1 hour after the booking record)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "Your call is booked",
    body: text(
      "Here is how to prep for it",
      "",
      "Hey {first}",
      "",
      "You stayed until the end, paid attention, and took action... I don't take that lightly. You know what that tells me? You're someone who sees an opportunity and moves on it. That's exactly the type of person who thrives in this community.",
      "",
      "I promised three bonuses to everyone who showed up and stuck it out, and I keep my word. They're in this email. Scroll down and they're yours.",
      "",
      "But first, your enrollment call is confirmed, and I want you to know that's not something we offer to everyone.",
      "",
      "Before your call, I want you to sit with something for a moment.",
      "",
      "The people who've built something real inside this community all needed something to change. They wanted income that didn't depend on one source. They wanted something they could grow, own, and one day hand off. And more than anything, they wanted their time back. Time with the people that matter. To not miss the moments that don't come back.",
      "",
      "That's why this call matters. Not because you have to join anything, but because this is the conversation that helps you figure out if this is the right next step for you. Keep me posted on how the call goes. Or better yet, ping me when you get in the community to let me know you joined!",
      "",
      "As promised, here are your three free bonuses.",
      "→ The Route Builder {link: Route Builder} In under 60 seconds, plug in your market, your income goal, and the time you have available. It'll show you what a vending route could realistically look like for your specific situation.",
      "→ The 90-Day Master Checklist {link: 90-Day Master Checklist} This is your roadmap for exactly what happens in the first 30, 60, and 90 days. No guessing, no overwhelm… just a clear, honest picture of what getting started actually looks like.",
      "",
      "You earned these! I highly suggest you use the route building quiz before your call. Come with your numbers. Come with your questions. Come ready for an honest conversation about whether this is the right fit for where you are right now.",
      "",
      "And I am going to be straight with you. This isn't for everyone. But you'll at least know if it is or isn't.",
      "",
      "Talk soon,",
      "Anthony Kolodziej / Vendingpreneurs",
      "",
      "PS: Can you hit reply and let me know either: what your favorite takeaway from the class was? Or what you'd like to know more about it?",
    ),
    verbatim: true,
    links: ["Route Builder", "90-Day Master Checklist"],
    flag: {
      issue:
        'It promises three bonuses but lists two, and the live version has the typo "booking you call".',
      fix: 'Anthony names the third bonus (or the email says two) and the typo becomes "booking your call".',
      owner: "Ivan",
      due: "Wed Oct 7",
    },
  },
  {
    id: "V3",
    phase: "booked",
    when: "about 1 hour after the booking email (seen once, for a booker)",
    channel: "voice",
    from: ANTHONY_EMAIL,
    body: "Ringless voicemail drop to someone who just booked a call. No body captured.",
    verbatim: false,
  },
  {
    id: "E23",
    phase: "booked",
    when: "timing unknown (pre-call nurture; workflow may still be a draft)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "Do this so you're on track",
    body: 'Preheader "These steps are crucial for your first 90 days in vending". Opens: "A successful vending business doesn\'t happen overnight, and I won\'t even tell you it happens in 90 days. But I can tell you this: if you follow the steps below for your first few months, you\'ll be set up for success well beyond day 90." Three phases: Days 1-30 research, machine selection and location targeting; Days 31-60 securing your first location and placing your machine; Days 61-90 launch, optimize and build toward your second location. Ends with a video link ("Still not sure if vending is for you?"). Signed Best, Anthony.',
    verbatim: false,
  },
  {
    id: "E24",
    phase: "booked",
    when: "timing unknown (pre-call nurture)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "Don't buy a vending machine… yet.",
    body: "Days 1-30 checklist: choose the right machine (don't buy used), learn the financial reality (gross revenue, COGS, revenue share, merchant and software fees, labor, net profit), identify 10-15 target locations narrowed to five, form an LLC and open a business bank account. Ends: by Day 30 you should have a machine type selected, a financial model understood and a shortlist of five targets.",
    verbatim: false,
  },
  {
    id: "E25",
    phase: "booked",
    when: "timing unknown (pre-call nurture)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "Day 31-60 should look like this",
    body: 'Preheader "A signed agreement, machine on order, and more." Land your first location (drive-by top five, identify the decision-maker, site walk), pitch it as an amenity not revenue share, use a simple agreement (placement, service frequency, revenue share, exclusivity, term), order the machine. Includes a pitch video link.',
    verbatim: false,
  },
  {
    id: "E26",
    phase: "booked",
    when: "timing unknown (pre-call nurture)",
    channel: "email",
    from: ANTHONY_EMAIL,
    subject: "What Days 61-90 actually look like",
    body: 'Preheader "An operating machine, scaling, and preparing for a second location." Machine arrives, set prices, stock 60-70%, remote monitoring, first 30 operating days, hire a part-time stocker (the J curve), lean on the community.',
    verbatim: false,
  },
];

export const COMMS_PHASES: readonly {
  id: CommsPhase;
  title: string;
  who: string;
}[] = [
  { id: "register", title: "At sign-up", who: "Everyone who registers" },
  {
    id: "before",
    title: "Before the webinar",
    who: "Everyone who registers, until the room starts",
  },
  {
    id: "dayof",
    title: "Webinar day",
    who: "Everyone who registers, from 3 hours before to 30 minutes after the start",
  },
  {
    id: "attended",
    title: "Attended, didn't book",
    who: "People who joined the room but did not book a call",
  },
  {
    id: "missed",
    title: "Missed it",
    who: "People who registered but did not attend",
  },
  {
    id: "booked",
    title: "Booked a call",
    who: "Anyone who books a call, and the pre-call nurture that follows",
  },
];

export const SWAP_ROWS: readonly SwapRow[] = [
  {
    step: "Registration page",
    today:
      "GHL page webinar.vendingpreneurs.com/home (form TsHS6bjzHkHakUa1ULxu); every ad points here.",
    after:
      "vendingpreneurs.com/masterclass for every ad. Same GHL workflow fires, plus Zoom, Close and the Meta registration event.",
    change:
      "Full switch for Tue Oct 13 (Adam, Oct 6). Liana moves all webinar ads on Wed Oct 7, after the Close zap is fixed and one test sign-up passes. GHL page stays up as the fallback.",
    owner: "Liana",
  },
  {
    step: "Confirmation page",
    today:
      "GHL /masterclass-thankyou-confirmation (also linked from the 24-hour text).",
    after:
      "vendingpreneurs.com/masterclass-confirmed (video, calendar buttons, 3 intake questions, Playbook offer).",
    change:
      "Live and showing Oct 13. The 24-hour text (S4) still links the GHL page: Ivan changes the link only.",
    owner: "Ivan",
  },
  {
    step: "Playbook page + checkout",
    today:
      "GHL /playbook ($67, anchor $199) and GHL /checkout; the Saturday email (E27) links GHL /playbook.",
    after:
      "vendingpreneurs.com/playbook, /playbook/checkout (GHL order form embedded, same $67 product), /playbook/thank-you.",
    change:
      "Live, with Anthony's current figures (47 locations, 84 machines, $116K), matching the GHL emails. The Saturday email (E27) moves to the site page. Purchase stays in GHL.",
    owner: "Ivan",
  },
  {
    step: "Replay page: registered, did not attend",
    today:
      "GHL /masterclass-replay-dna via the dna-replay, dna-sms-replay and dna-book-your-call short links (utm sept15_end_cta, sept01_end_cta).",
    after: "vendingpreneurs.com/masterclass-replay-dna",
    change:
      "Retarget the three Bitly links to the site page with utm_content oct06_end_cta (the Oct 6 replay week), then oct13_end_cta after Oct 13. Destination only; never edit GHL workflows. Expiry Sun 9 PM CT.",
    owner: "Ivan",
  },
  {
    step: "Replay page: attended, did not book",
    today:
      "GHL /masterclass-replay-adnb via the adnb-replay, adnb-sms and adnb-booking-calendar short links (utm sept01, cut-off anchor).",
    after: "vendingpreneurs.com/masterclass-replay-adnb",
    change:
      "Retarget the three Bitly links to the site page with oct06_end_cta, no anchor. Destination only.",
    owner: "Ivan",
  },
  {
    step: "Replay page: Meta retargeting",
    today: "GHL /masterclass-replay-meta (same scoring form).",
    after: "vendingpreneurs.com/masterclass-replay-meta",
    change:
      "Liana points the retargeting ads at the site page with the same UTMs as the registration ads, when she moves the registration ads.",
    owner: "Liana",
  },
  {
    step: "Replay page: advisory team",
    today:
      "GHL /masterclass-replay-advisory-team-798452 (replay only, sent by the sales team).",
    after: "vendingpreneurs.com/masterclass-replay-advisory",
    change:
      "Sales team sends the site link from Wed Oct 7. Pearl updates the saved reply.",
    owner: "Pearl",
  },
  {
    step: "Night-of booking (/start)",
    today:
      "start-vending.com redirects to vendingpreneurs.com/start with utm_content oct06_end_cta.",
    after: "Same host, utm_content oct13_end_cta.",
    change:
      "Roll the forwarding to oct13_end_cta before the room on Tue Oct 13 (after the Oct 6 booking window).",
    owner: "Ivan",
  },
  {
    step: "Links in emails and texts (Bitly)",
    today:
      "Six booking.vendingpreneurs.com short links go to GHL replay pages with old utm_content; seven legacy links (masterclass, watch-the-replay, free-advisory-call and others) carry apr21 to July14 values.",
    after:
      "The six go to the site replay pages with the week's utm_content; legacy links fixed or confirmed unused.",
    change:
      "Ivan retargets the six by Wed Oct 7 and lists which messages still use the legacy links.",
    owner: "Ivan",
  },
  {
    step: "Paid ads",
    today: "All Meta webinar ads send to the GHL /home page.",
    after:
      "All webinar ads send to vendingpreneurs.com/masterclass with utm_source=meta&utm_medium={{adset.id}}&utm_campaign=VP-Masterclass&utm_content={{ad.id}}.",
    change:
      "LAST step, Wed Oct 7. A URL change sends each ad back through review and can restart learning, so do it once, early in the week, never Monday.",
    owner: "Liana",
  },
  {
    step: "Meta CAPI (Complete Registration)",
    today:
      'GHL workflow "Webinar Leads to Meta Complete Registration" fires on the webinar-registrant tag.',
    after:
      "Site sign-ups get the same tag and fire the same workflow. No browser ids (fbp/fbc) on site contacts, so match quality may drop.",
    change:
      "One test sign-up on the site with Events Manager open: Complete Registration arrives, note Event Match Quality. Before any ad moves.",
    owner: "Liana",
  },
  {
    step: "Zoom, Close and Sheet zaps",
    today:
      "Zoom registrar is on Oct 13 (every new registrant gets an Oct 13 link). GHL to Close is still on the Oct 6 pipeline: 6 Oct 13 registrants have no Close lead.",
    after:
      "Every zap on the Oct 13 webinar (82546367729) and pipeline (5uuvIbBhU6oGD2JPrANk).",
    change:
      "Ivan rolls the Close zap first thing Wed Oct 7 and backfills the missing leads; Sheet row checked; Particpate > GHL and Calendly > GHL rolled before the room.",
    owner: "Ivan",
  },
];

export const LAUNCH_CHECKLIST: readonly ChecklistItem[] = [
  // -------------------------------------------------------------- decisions
  // ----------------------------------------------------------------- Ivan
  {
    item: "Roll the GHL to Close lead zap to the Oct 13 pipeline and backfill the leads it missed",
    owner: "Ivan",
    due: "Wed Oct 7, 9 AM CT",
    status: "open",
    note: "6 Oct 13 registrants since 7:41 PM CT Oct 6 have no Close lead; Zoom side already works.",
  },
  {
    item: "Retarget the six booking short links to the site replay pages with oct06_end_cta",
    owner: "Ivan",
    due: "Wed Oct 7",
    status: "open",
    note: "dna-replay, dna-sms-replay, dna-book-your-call to /masterclass-replay-dna; adnb-replay, adnb-sms, adnb-booking-calendar to /masterclass-replay-adnb. Destination only.",
  },
  {
    item: "Confirm the Sheet row zap writes Oct 13 registrants to an OCT 13 tab",
    owner: "Ivan",
    due: "Wed Oct 7",
    status: "open",
  },
  {
    item: "Change the link in the 24-hour text (S4) and the Saturday email (E27) to the site pages",
    owner: "Ivan",
    due: "Thu Oct 8",
    status: "open",
    note: "S4 to /masterclass-confirmed, E27 to /playbook. Links only.",
  },
  {
    item: "Roll Particpate > GHL to Zoom 82546367729 and Calendly > GHL to the Oct 13 pipeline",
    owner: "Ivan",
    due: "Tue Oct 13, noon CT",
    status: "open",
    note: "Calendly stays on Oct 6 until its 72-hour booking window closes.",
  },
  {
    item: "Roll start-vending.com forwarding to oct13_end_cta",
    owner: "Ivan",
    due: "Tue Oct 13, noon CT",
    status: "open",
  },
  {
    item: "List which live messages still use the legacy short links (masterclass, watch-the-replay, free-advisory-call, ready-for-my-call, training-call)",
    owner: "Ivan",
    due: "Fri Oct 9",
    status: "open",
    note: "They carry apr21 to July14 utm_content, so their clicks credit old rooms.",
  },
  // ---------------------------------------------------------------- Liana
  {
    item: "Test sign-up on vendingpreneurs.com/masterclass with Events Manager open; note Event Match Quality",
    owner: "Liana",
    due: "Wed Oct 7",
    status: "open",
    note: "After Ivan's Close fix, so the same test proves GHL, Zoom, Close, Sheet and the board. We delete the test lead after.",
  },
  {
    item: "Move every webinar ad (and the retargeting ads) to the site pages with the standard UTMs",
    owner: "Liana",
    due: "Wed Oct 7",
    status: "open",
    note: "Last step. utm_source=meta&utm_medium={{adset.id}}&utm_campaign=VP-Masterclass&utm_content={{ad.id}}.",
  },
  // ---------------------------------------------------------------- others
  {
    item: "Send the domain verification code for vendingpreneurs.com from Business Manager",
    owner: "Adam",
    due: "Wed Oct 7",
    status: "open",
    note: "We add the TXT record at ClouDNS.",
  },
  {
    item: "Sales team sends the site advisory replay link instead of the GHL one",
    owner: "Pearl",
    due: "Wed Oct 7",
    status: "open",
    note: "vendingpreneurs.com/masterclass-replay-advisory",
  },
  {
    item: "Name the third live bonus and say whether the fast-action discount exists",
    owner: "Anthony",
    due: "Fri Oct 9",
    status: "open",
    note: "The 15-minute text promises three; the booked email lists two.",
  },
  {
    item: "Open /playbook/checkout and /masterclass-replay-dna on a phone and go through to the order form and Calendly (no purchase)",
    owner: "Team",
    due: "Thu Oct 8",
    status: "open",
  },
  // ------------------------------------------------------------------ done
  {
    item: "Anthony's figures match everywhere: 47 locations, 84 machines, $116,352.88",
    owner: "Site (done)",
    due: "Wed Oct 7",
    status: "done",
    note: "Site /playbook now uses the numbers Anthony's GHL emails already send.",
  },
  {
    item: "Zoom reminder emails on for Oct 13 (1 week, 1 day, 1 hour), same as Oct 6",
    owner: "Site (done)",
    due: "Wed Oct 7",
    status: "done",
    note: "Set through the Zoom API and read back.",
  },
  {
    item: "Board counts Oct 13 registrants under the tag GHL uses (oct13-webinar)",
    owner: "Site (done)",
    due: "Wed Oct 7",
    status: "done",
    note: "No workflow edit needed.",
  },
  {
    item: "Oct 13 Zoom webinar created (82546367729, 7:30 PM CDT)",
    owner: "Ivan",
    due: "Tue Oct 6",
    status: "done",
    note: "Found and registered on the board 2026-10-07.",
  },
  {
    item: "GHL custom values on Oct 13 (date, time, Q&A Thu Oct 8, AddEvent, Q&A link)",
    owner: "Site (done)",
    due: "Tue Oct 6",
    status: "done",
    note: "Read live; AddEvent opens the Oct 13 Zoom registration.",
  },
  {
    item: "New registrants land in the Oct 13 pipeline with an Oct 13 Zoom link",
    owner: "Site (done)",
    due: "Tue Oct 6",
    status: "done",
    note: "Checked on every registrant since the Oct 6 room.",
  },
  {
    item: "Site pages live for Oct 13, drop-off tracking on (PostHog and GA4)",
    owner: "Site (done)",
    due: "Tue Oct 6",
    status: "done",
    note: "All nine pages return the live page; PostHog events and replays arrive.",
  },
];

/** Section copy for the briefing's messages, swap map and checklist. */
export const COMMS_COPY = {
  messagesHeading: "Every message they get",
  messagesIntro:
    "Everything GoHighLevel sends after someone registers, in the order they receive it, copied from messages that actually went out. The swap keeps every message in GoHighLevel; only the links inside them move to the site. Tap a message to read it in full. Anything in red needs fixing before Tue Oct 13 and names who fixes it.",
  fixListHeading: "Fix before Oct 13",
  swapHeading: "What changes at the swap",
  swapIntro:
    "Step by step: what runs today, what runs from Oct 13, and who makes the change. The GoHighLevel pages stay up as the fallback; nothing in GoHighLevel is turned off.",
  checklistHeading: "Who does what before Oct 13",
  checklistIntro:
    "Decisions first, then one short list per person, soonest first. The ads move last, once the red lines in “Are we ready for Oct 13?” are closed.",
  jumpLinks: [
    { href: "#readiness-heading", label: "Ready?" },
    { href: "#checklist-heading", label: "Who does what" },
    { href: "#messages-heading", label: "Every message" },
    { href: "#swap-map-heading", label: "What changes" },
  ],
} as const;

/** Live check 2026-10-07 (vp-webinars/event-log/2026-10-13.md). */
export const READINESS = {
  heading: "Are we ready for Oct 13?",
  verdict:
    "Full switch for Tue Oct 13. Pages, Zoom, custom values and tracking are ready. One red line (the Close zap) closes Wednesday morning, then one test sign-up, then the ads move.",
  checkedOn: "Checked against the live systems Tue Oct 6, 11 PM CT",
  rows: [
    {
      area: "Zoom and GHL registration",
      status: "green",
      line: "Oct 13 webinar exists (7:30 PM CDT). Every registrant since the Oct 6 room is in the Oct 13 pipeline with an Oct 13 Zoom link.",
    },
    {
      area: "Close",
      status: "red",
      line: "The GHL to Close zap is still on the Oct 6 pipeline: 6 Oct 13 registrants have no Close lead. Ivan, Wed 9 AM.",
    },
    {
      area: "Messages and links",
      status: "yellow",
      line: "Custom values are on Oct 13. Six short links still go to GHL replay pages with old UTMs; the 24-hour text and Saturday email link GHL pages.",
    },
    {
      area: "Meta ads and tracking",
      status: "yellow",
      line: "Test sign-up in Events Manager and domain verification first; then Liana moves every ad with the standard UTMs.",
    },
    {
      area: "Drop-off tracking",
      status: "green",
      line: "PostHog and GA4 get every step: page views, form started, registered, calendar adds, Playbook and checkout clicks, purchases.",
    },
    {
      area: "Zoom reminders",
      status: "green",
      line: "Zoom's reminder emails are on for Oct 13 (1 week, 1 day, 1 hour), same as Oct 6.",
    },
  ],
} as const;

export type ReadinessStatus = "green" | "yellow" | "red";
