#!/usr/bin/env python3
"""Builds supabase/migrations/20260929124000_seo_seed.sql from the SEO strategy
run's deliverables (default ~/Desktop/vp-seo-output). Re-runnable; the SQL it
writes is idempotent (on conflict do nothing), so pasting it twice is safe and
never overwrites a status someone changed in /admin/seo.

Usage: python3 scripts/seo/build-seed.py [path-to-vp-seo-output]
"""
import csv, datetime, glob, json, os, re, sys

SRC = os.path.expanduser(sys.argv[1] if len(sys.argv) > 1 else "~/Desktop/vp-seo-output")
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "supabase/migrations/20260929124000_seo_seed.sql")
sys.path.insert(0, os.path.join(SRC, "scripts"))
from pieces import PIECES  # noqa: E402

# The production sequence (workbook "Production Sequence" sheet) with the
# changes recommended in 00-README.md applied: HUB 2 -> P1 week 9, 2.1/2.2 ->
# weeks 5-6, 2.4 -> week 11, 1.4 -> P1, 7.19 Washington added.
SEQUENCE = {
    "P1": {"HUB 1": 1, "1.1": 1, "HUB 4": 1, "HUB 3": 2, "3.2": 3, "3.3": 4, "3.1": 4,
           "HUB 5": 5, "5.1": 5, "2.1": 5, "5.2": 6, "2.2": 6, "HUB 6": 7, "6.1": 7,
           "6.2": 8, "1.5": 8, "HUB 2": 9, "2.3": 10, "1.4": 10},
    "P2": {"2.4": 11, "7.1": 11, "7.2": 12, "7.3": 12, "3.4": 13, "3.5": 13, "6.5": 14,
           "4.2": 14, "4.1": 15, "5.3": 15, "HUB 7": 16, "7.4": 16, "7.5": 17, "1.2": 17,
           "7.6": 18, "7.7": 18, "7.8": 18, "7.9": 19, "7.10": 19, "7.11": 19,
           "7.12": 20, "7.13": 20, "7.14": 20},
    "P3": {"3.6": 21, "4.3": 21, "4.4": 22, "6.3": 23, "6.4": 23, "7.15": 24, "7.16": 24,
           "7.17": 24, "7.18": 24, "7.19": 24, "4.5": 25, "4.6": 25, "5.5": 25, "5.6": 25,
           "6.6": 25, "2.5": 25, "2.6": 25, "2.7": 25},
}
PRIMARY_OVERRIDE = {"2.3": "combo vending machine", "1.8": "vending machine side hustle"}
EXTRA = [("7.19", 7, "vending-machine-business-washington", "Washington Vending Guide",
          "vending machine laws washington state")]
# Same page as another piece: tracked, never published or tasked twice.
ALIAS = {"HUB 4": "1.1", "5.3": "3.4", "5.6": "7.18"}
WEEK1 = datetime.date(2026, 9, 28)
OWNER = "Adam"  # Adam owns SEO (2026-09-29); every seeded task is his  # Monday the plan starts


def q(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, list):
        return "array[" + ",".join(q(x) for x in v) + "]::text[]" if v else "'{}'::text[]"
    return "'" + str(v).replace("'", "''") + "'"


def num(v):
    m = re.match(r"^\s*([\d,]+(?:\.\d+)?)\s*$", v or "")
    return int(float(m.group(1).replace(",", ""))) if m else None


def due(week):
    return (WEEK1 + datetime.timedelta(days=(week - 1) * 7 + 4)).isoformat()


matrix = {r["piece"]: r for r in csv.DictReader(open(os.path.join(SRC, "priority-matrix.csv")))}
drafts = {}
for path in sorted(glob.glob(os.path.join(SRC, "02-p1-drafts/*.md"))):
    name = os.path.basename(path)
    text = open(path).read()
    m = re.match(r"\d+-(hub(\d)|spoke([\d.]+))", name)
    pid = f"HUB {m.group(2)}" if m.group(2) else m.group(3).rstrip(".")
    flags = [re.sub(r"\s+", " ", x.group(0).replace("**", "")).strip(" >*|")
             for x in re.finditer(r"[^\n]{0,80}VERIFY[^\n]{0,280}", text)]
    wc = re.search(r"Word count \(body\) \| ([\d,]+)", text)
    drafts[pid] = {"file": name, "flags": flags, "words": num(wc.group(1)) if wc else None}

lines = ["-- Seed for the SEO command center. Generated by scripts/seo/build-seed.py",
         "-- from the 2026-09-28 strategy run. Idempotent: on conflict do nothing.", ""]

rows = []
for pid, hub, slug, title, kw in list(PIECES) + EXTRA:
    prio, week = next(((p, w[pid]) for p, w in SEQUENCE.items() if pid in w), (None, None))
    prio = prio or (matrix.get(pid, {}).get("phase") or "P3")
    d = drafts.get(pid)
    status = "planned" if not d else ("verify_needed" if d["flags"] else "in_review")
    notes = f"Same page as {ALIAS[pid]}." if pid in ALIAS else None
    rows.append("(" + ",".join(q(x) for x in [
        pid, hub, title, slug, PRIMARY_OVERRIDE.get(pid, kw), prio, week, status,
        d["file"] if d else None, len(d["flags"]) if d else 0, d["words"] if d else None, notes,
    ]) + ")")
lines.append("insert into public.seo_content_pieces (id, hub, title, slug, primary_keyword, priority, sequence_week, status, draft_file, verify_flags, word_count, notes) values")
lines.append(",\n".join(rows) + "\non conflict (id) do nothing;\n")

kw_rows, seen = [], set()
for r in csv.DictReader(open(os.path.join(SRC, "keyword-tracking-list.csv"))):
    k = r["keyword"].strip().lower()
    if not k or k in seen:
        continue
    seen.add(k)
    pieces = [p.strip() for p in (r["piece"] or "").split(",") if p.strip()]
    kw_rows.append("(" + ",".join(q(x) for x in [
        k, pieces, r["hub"] or None, "primary" if r["role"] == "primary" else "supporting",
        num(r["volume"]), num(r["kd"]), None,
    ]) + ")")
for pid, kw in PRIMARY_OVERRIDE.items():
    if kw not in seen:
        seen.add(kw)
        kw_rows.append("(" + ",".join(q(x) for x in [kw, [pid], None, "primary", None, None, None]) + ")")
lines.append("insert into public.seo_keywords (keyword, piece_ids, hub, role, volume, kd, cpc) values")
lines.append(",\n".join(kw_rows) + "\non conflict (keyword) do nothing;\n")

tasks = []
def task(key, type_, title, detail=None, piece=None, prio="medium", due_date=None, phase=None, url=None):
    tasks.append("(" + ",".join(q(x) for x in [
        key, type_, piece, url, title, detail, prio, due_date, phase, "seed", OWNER]) + ")")

all_pieces = {p[0]: p for p in list(PIECES) + EXTRA}
for pid, week in SEQUENCE["P1"].items():
    if pid in ALIAS:
        continue
    slug, title = all_pieces[pid][2], all_pieces[pid][3]
    d = drafts.get(pid)
    detail = (f"Draft ready: Desktop/vp-seo-output/02-p1-drafts/{d['file']}. " if d else "No draft yet. ") + \
        "Build it block by block in the page builder (the document importer keeps only 8 sections), link only to live pages, then request indexing in Search Console."
    task(f"publish:{pid}", "publish", f"Publish {pid}: {title}", detail, pid, "high", due(week), url=f"/resources/{slug}")
for pid, d in drafts.items():
    if d["flags"]:
        task(f"verify:{pid}", "verify_facts",
             f"Check {len(d['flags'])} VERIFY flag{'s' if len(d['flags']) > 1 else ''} in {pid} before publishing",
             "\n".join(f"- {f}" for f in d["flags"]), pid, "high",
             due(max(1, SEQUENCE['P1'].get(pid, 2) - 1)))
TECH = [
    ("importer-cap", "Let the page builder import more than 8 sections", "src/lib/page-builder/document-import.ts caps imports at MAX_IMPORTED_BLOCKS = 8 and silently drops the rest. Every hub draft has more than 8 H2s. Raise or split the cap, or build pages block by block.", "urgent", 1),
    ("business-plan-download", "Build the business plan template download", "The biggest quick win (1.1, 8,100/mo, KD 0) promises a downloadable template. Replace {{DOWNLOAD_URL_BUSINESS_PLAN}} (4 uses) with its URL.", "high", 1),
    ("permit-checklist-download", "Build the permit checklist download", "HUB 3 and 3.1 promise it. Replace {{DOWNLOAD_URL_PERMIT_CHECKLIST}} (5 uses).", "high", 2),
    ("cta-targets", "Create the community and training link targets", "Drafts use {{JOIN_COMMUNITY_URL}} (10) and {{TRAINING_URL}} (6). No route exists yet.", "high", 1),
    ("booking-seo", "Add a /booking-seo variant for organic attribution", "Follow the /booking-youtube pattern so booked calls from /resources pages are countable in Close.", "medium", 2),
]
for key, title, detail, prio, week in TECH:
    task(f"technical:{key}", "technical", title, detail, None, prio, due(week))
ROADMAP = [
    ("Foundation", "Confirm Search Console and GA4 access", "Done 2026-09-28: sc-domain:vendingpreneurs.com is the domain property and the service account reads it. Data starts 2025-11-26."),
    ("Foundation", "Open the DataForSEO account and add $10", "Adam. Steps in .claude/specs/2026-09-28-seo-command-center.md section 6. Then add DATAFORSEO_LOGIN / DATAFORSEO_PASSWORD to .env.local and Vercel."),
    ("Foundation", "Baseline: Search Console backfill, first rank pull, GA4 organic baseline", "Backfill: /api/admin/search-console-sync/run?days=500. First rank pull: /api/admin/seo-ranks/run?full=1 once DataForSEO is connected."),
    ("Foundation", "Weekly KPI tracking live", "The /admin/seo Overview tab replaces the spreadsheet template."),
    ("Content engine", "Publish the P1 sequence at 3-4 pieces a week", "17 drafts are ready; clear each draft's VERIFY flags first."),
    ("Content engine", "Interlink every published page", "Use the interlinking map; never link to a page that is not live. The Content Plan tab flags pages with fewer than 2 live inbound links."),
    ("Content engine", "Request indexing for each new URL in Search Console", "URL Inspection, then Request indexing. Track indexed within 14 days."),
    ("Content engine", "Content scoring pass", "Claude now; Profound after 20+ pages are live."),
    ("Optimization", "Bi-weekly live SERP scrape and trigger list", "Automated: the Monday trigger job opens tasks for Kody's 7 triggers."),
    ("Optimization", "Act on quick-win alerts", "Striking distance, plateau, slipping and declining pages appear as tasks every Monday."),
    ("Optimization", "Which mediums rank: add platform content where YouTube or LinkedIn ranks", "When a YouTube or LinkedIn result ranks for a target keyword, create the matching platform piece."),
    ("Optimization", "Backlink outreach", "07-task7 section 4: YouTube descriptions link to /resources first, then partner pages, podcasts, data PR."),
    ("Paid", "Google Ads on core conversion queries only", "Core conversion queries, direct competitor terms, brand campaign. No broad match or AI expansion. UTM the triggering search term. Monthly report fed to Claude."),
    ("Local", "State pages from markets with existing operators", "Cascade state pages from markets with operators nearby, with human-verified permits."),
    ("Decisions", "Ahrefs vs DataForSEO", "Start with DataForSEO. Revisit Ahrefs after 20+ pages are live."),
    ("Decisions", "Profound vs Claude for content scoring", "Claude first; Profound after 20+ pages."),
    ("Decisions", "Guided freemium trial with 50 credits + webinar", "Agreed direction, outside SEO scope. Listed only."),
]
for i, (phase, title, detail) in enumerate(ROADMAP):
    task(f"roadmap:{i + 1:02d}", "roadmap", title, detail, None, "medium", None, phase)
lines.append("insert into public.seo_tasks (seed_key, type, piece_id, url, title, detail, priority, due_date, phase, created_by, owner) values")
lines.append(",\n".join(tasks) + "\non conflict (seed_key) do nothing;\n")
lines.append("-- Search Console access is confirmed; mark that roadmap item done.")
lines.append("update public.seo_tasks set status = 'done', done_at = now() where seed_key = 'roadmap:01' and status = 'open';\n")

open(OUT, "w").write("\n".join(lines))
print(f"{len(rows)} pieces, {len(kw_rows)} keywords, {len(tasks)} tasks -> {os.path.relpath(OUT, ROOT)}")

# The interlinking map as a module /admin/seo imports (no file reads at runtime).
links = [(r["source"].strip(), r["target"].strip())
         for r in csv.DictReader(open(os.path.join(SRC, "interlinking-map.csv")))]
TS = os.path.join(ROOT, "src/lib/seo/interlinking-map.ts")
with open(TS, "w") as f:
    f.write("// Generated by scripts/seo/build-seed.py from interlinking-map.csv\n")
    f.write("// (2026-09-28 strategy run, Task 4). Planned links: [from piece, to piece].\n")
    f.write("export const PLANNED_LINKS: ReadonlyArray<readonly [string, string]> = [\n")
    f.write("".join(f"  [{json.dumps(a)}, {json.dumps(b)}],\n" for a, b in links))
    f.write("];\n")
print(f"{len(links)} planned links -> {os.path.relpath(TS, ROOT)}")
